### PR TITLE
added pypy support

### PR DESCRIPTION
**Pull request by yeger00**

### CODE REVIEW

**Comment by hobbestigrou** [comment]
Please can you resolved conflicts.

**Comment by yeger00** [comment]
Fixed the conflicts

**Comment by hobbestigrou** [comment]
Ok for me, I agree.

**Comment by bialix** [comment]
I'm sorry to say but part of changes in this patch are just wrong. In details, code like this
`
res = run('%(python_cmd)s %(pip_cmd)s --version 2>/dev/null' % locals())
`

Let's convert string formatting to default values:

`
res = run('python pip --version 2>/dev/null')
`

The code above will work only if there is `pip` script in current directory which is not true I suppose.

So, the correct change should be actually:

`res = run('%(python_cmd)s -m %(pip_cmd)s --version 2>/dev/null' % locals())`

Which will be translated into

`
res = run('python -m pip --version 2>/dev/null')
`

**Pull request merged**
