### PR TITLE
Added fabric>=1.6.0 and . (in editable mode) to dev requirements (And CRUX Support)

### PR DESCRIPTION
**Pull request by prologic**
Just less typing to get a development version up and running.

### CODE REVIEW

**Comment by prologic** [comment]
bump

**Comment by hobbestigrou** [comment]
Please can you resolved conflicts.

**Comment by prologic** [comment]
@hobbestigrou Done! (~2 years later!)

**Comment by hobbestigrou** [comment]
Ok for me, I agree.

**Pull request merged**
