### PR TITLE
Support for Bazaar VCS

### PR DESCRIPTION
**Pull request by jitakirin**
Hi, this implements support for bazaar VCS, similar to the currently existing git and mercurial.
Includes tests.
Comments welcome.

### CODE REVIEW

**Comment by hobbestigrou** [comment]
Please can you resolved conflicts.

**Comment by jitakirin** [comment]
Yip, will have a look.

**Comment by jitakirin** [comment]
Done now, ta

**Comment by hobbestigrou** [comment]
Ok for me, I agree.

**Pull request merged**
